.data?
modelOmega dd ?
modelInsertedPinNumber dd ?
modelScore dd ?
.data

;É¾µô£¡£¡£¡£¡£¡£¡£¡£¡£¡
;szMiddle1Fmt byte "			%d",0ah,0
;szMiddle2Fmt byte "%d",0ah,0
;szMiddle3Fmt byte "%d:Åö×²À²",0ah,0
;szMiddle4Fmt byte "cdeg:%d",0ah,0

modelNowDifficulty dd 5


KeyboardEvent PROTO C:dword
Window0Type0 PROTO C
Window0Type1 PROTO C
Window0Type2 PROTO C
Window1Type0 PROTO C
Window1Type1 PROTO C
Window1Type2 PROTO C
Window2Type0 PROTO C
Window2Type1 PROTO C
Window3Type0 PROTO C
Window3Type1 PROTO C
InitParam PROTO C
InitWindow PROTO C